import type { LucideIcon } from 'lucide-react'

import {
  BarChart3,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Brain,
  Briefcase,
  Check,
  Crown,
  Dumbbell,
  Flame,
  FlaskConical,
  GraduationCap,
  HeartCrack,
  HeartPulse,
  Landmark,
  Languages,
  Library,
  Lightbulb,
  Lock,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  PartyPopper,
  Plane,
  Rocket,
  RotateCcw,
  Sparkles,
  SpellCheck,
  Sprout,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Utensils,
  Waves,
  X,
  Zap,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  BarChart3,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Brain,
  Briefcase,
  Check,
  Crown,
  Dumbbell,
  Flame,
  FlaskConical,
  GraduationCap,
  HeartCrack,
  HeartPulse,
  Landmark,
  Languages,
  Library,
  Lightbulb,
  Lock,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  PartyPopper,
  Plane,
  Rocket,
  RotateCcw,
  Sparkles,
  SpellCheck,
  Sprout,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Utensils,
  Waves,
  X,
  Zap,
}

/**
 * Renders a Lucide icon by name (data-driven icons from course/achievements).
 * Falls back to a neutral sparkle icon for unknown names.
 */
export function UiIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = ICONS[name] ?? Sparkles
  return <Icon size={size} aria-hidden="true" />
}
